config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :appartements, :messages
  root to: "pages#home"
  get 'home', to: "pages#home"
end

app/models/appartement.rb
class Appartement < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :appartement
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/appartement_controller.rb
class AppartementController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @appartements = policy_scope(Appartement)
  end

  def new # return HTML form for create
    @appartement = Appartement.new
    authorize @appartement
  end

  def create
    @appartement = Appartement.new(appartement_params)
    authorize @appartement
    @appartement.user_id = current_user.id
    if @appartement.save
      redirect to appartement_path(@appartement)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @appartement.update(appartement_params)
    redirect_to appartement_path(@appartement)
  end

  def destroy
    @appartement = Appartement.find_by(params[:id])
    @appartement.destroy
  end

  private

  def set_appartement
    @appartement = Appartement.find(params[:id])
    authorize @appartement
  end

  def appartement_params
    params.require(:appartement).permit(:price, :description, :adress, :postcode, :city)
  end
end

app/controllers/appartements_controller.rb
class AppartementsController < ApplicationController
  before_action :set_appartement, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @appartements = policy_scope(Appartement)
    respond_to do |format|
      format.html
      format.xml { render xml: @appartements }
      format.json { render json: @appartements }
    end
  end

  def new
    @appartement = Appartement.new
    authorize @appartement
  end

  def create
    @appartement = Appartement.new(appartement_params)
    authorize @appartement
    @appartement.user_id = current_user.id
    if @appartement.save
      redirect_to appartement_path(@appartement)
    else
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml { render xml: @appartements }
      format.json { render json: @appartements }
    end
  end

  def edit
  end

  def update
    @appartement.update(appartement_params)
    redirect_to appartement_path(@appartement)
  end

  def destroy
    @appartement = Appartement.find_by(params[:id])
    @appartement.destroy
  end

  private

  def set_appartement
    @appartement = Appartement.find(params[:id])
    authorize @appartement
  end

  def appartement_params
    params.require(:appartement).permit(:price, :description, :adress, :postcode, :city)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_params, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @messages = policy_scope(Message)
    respond_to do |format|
      format.html
      format.xml { render xml: @messages }
      format.json { render json: @messages }
    end
  end

  def new
    @message = Message.new
    authorize @message
  end

  def create
    @message = Message.new(message_params)
    authorize @message
    @message.user_id = current_user.id
    @message.appartement_id = params[:id]
    if @message.save
      redirect to message_path(@message)
    else
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml { render xml: @messages }
      format.json { render json: @messages }
    end
  end

  def edit
  end

  def update
    @message.update(message_params)
    redirect_to messages_path(@message)
  end

  def destroy
    @message = Message.find_by(params[:id])
    @message.destroy
  end

  private

  def set_message
    @message = Message.find(params[:id])
    authorize @message
  end

  def message_params
    params.require(:message).permit(:contenu)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/appartement_helper.rb
module AppartementHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appartements/edit.html.erb
<h1>Edit appartements</h1>

<%= simple_form_for @appartement do |f| %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :postcode %>
  <%= f.input :city %>
  <%= f.submit %>
<% end %>

app/views/appartements/index.html.erb
<h1>All appartements</h1>

<ul>
  <% @appartements.each do |appartement| %>
    <li><%= link_to appartement.address, appartement_path(Appartement) %></li>
  <% end %>
</ul>

<%= link_to "Add appartements", new_appartement_path %>

app/views/appartements/new.html.erb
<h1>Add appartements</h1>

<%= simple_form_for @appartement do |f| %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :postcode %>
  <%= f.input :city %>
  <%= f.submit %>
<% end %>

app/views/appartements/show.html.erb
<h1>Appartement</h1>

<ul>
  <li><%= @appartement.price %>€</li>
  <li><%= @appartement.description %></li>
  <li><%= @appartement.address %></li>
  <li><%= @appartement.postcode %> <%= @appartement.city %></li>
</ul>

<% if policy(@appartement).edit? %>
  <%= link_to 'Edit', edit_appartement_path(@appartement) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br><br>
    <%= link_to 'Home', home_path %>
    <%= link_to 'Sign in', new_user_session_path unless user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete if user_signed_in? %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/message/edit.html.erb
<h1>Edit message</h1>

<%= simple_form_for @message do |f| %>
  <%= f.input :contenu %>
  <%= f.submit %>
<% end %>

app/views/message/index.html.erb
<h1>All messages</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= message.contenu %></li>
    <li><%= link_to message.appartement_id, message_path(message) %></li>
  <% end %>
</ul>

<%= link_to "Add messages", new_message_path %>

app/views/message/new.html.erb
<h1>Add message</h1>

<%= simple_form_for @message do |f| %>
  <%= f.input :contenu %>
  <%= f.submit %>
<% end %>

app/views/message/show.html.erb
<h1>Message</h1>

<ul>
  <li> <%= @message.contenu %> </li>
  <li> <%= @message.appartement_id %> </li>
  <li> <%= @message.user_id %> </li>
</ul>

<% if policy(@message).edit? %>
  <%= link_to 'Edit', edit_message_path(@message) %>
<% end %>

app/views/pages/home.html.erb
<h1>Home page</h1>

<h2>Appartements short list</h2>
<ul>
<% # render appartement short list with a link to appartements#index %>
</ul>